import { DL_API_PREFIX_KEY } from 'consts/common';
import { EProductElements } from 'types/product';

enum ETemplates {
  PRODUCT_LISTING = `${DL_API_PREFIX_KEY}PRODUCT_LISTING`,
  PRODUCT_LISTING_HOTSPOT = `${DL_API_PREFIX_KEY}PRODUCT_LISTING_HOTSPOT`,
  BASKET_PAGE_HOTSPOT = `${DL_API_PREFIX_KEY}BASKET_PAGE_HOTSPOT`,

  PRODUCT_DETAILS_ASSOCIATED_ONE = `${DL_API_PREFIX_KEY}PRODUCT_DETAILS_ASSOCIATED_ONE`,
  PRODUCT_DETAILS_ASSOCIATED_TWO = `${DL_API_PREFIX_KEY}PRODUCT_DETAILS_ASSOCIATED_TWO`,
  PRODUCT_DETAILS_ASSOCIATED_THREE = `${DL_API_PREFIX_KEY}PRODUCT_DETAILS_ASSOCIATED_THREE`,
  PRODUCT_DETAILS_ASSOCIATED_FOUR = `${DL_API_PREFIX_KEY}PRODUCT_DETAILS_ASSOCIATED_FOUR`,
  PRODUCT_DETAILS_PRODUCTS_ZONE_ONE = `${DL_API_PREFIX_KEY}PRODUCT_DETAILS_PRODUCTS_ZONE_ONE`,

  MAIN_PAGE_HOTSPOT_ONE = `${DL_API_PREFIX_KEY}MAIN_PAGE_HOTSPOT_ONE`,
  MAIN_PAGE_HOTSPOT_TWO = `${DL_API_PREFIX_KEY}MAIN_PAGE_HOTSPOT_TWO`,
  MAIN_PAGE_HOTSPOT_THREE = `${DL_API_PREFIX_KEY}MAIN_PAGE_HOTSPOT_THREE`,
  MAIN_PAGE_HOTSPOT_FOUR = `${DL_API_PREFIX_KEY}MAIN_PAGE_HOTSPOT_FOUR`,
}

type TContentMap = {
  selector: string;
  replace: string[];
  canBeNull?: boolean;
  prepareValue?: (item: Element) => string;
};

type TContentMapItem = {
  key: string;
  map: TContentMap[];
};

type TReplaceContentMap = Record<
  ETemplates,
  Record<EProductElements, TContentMapItem>
>;

export { ETemplates };
export { TReplaceContentMap, TContentMapItem };
